# Generated by Django 5.0.4 on 2024-05-04 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleador', '0002_alter_empleado_apellido_alter_empleado_cuil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_notificacion', models.DateField(auto_now=True, verbose_name='Fecha de Notificación')),
                ('tipo', models.CharField(choices=[('1', 'Certificado de enfemedad'), ('2', 'Reclamos'), ('3', 'Permisos Especiales'), ('4', 'Solicitud de Vacaciones'), ('5', 'Envío de CBU'), ('6', 'Renuncia'), ('7', 'Otros')], max_length=20, verbose_name='Tipo')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='archivos/recibos/', verbose_name='Archivo adjunto')),
                ('visto', models.BooleanField(default=False, editable=False, verbose_name='Visto')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleador.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name_plural': 'Notificaciones',
            },
        ),
    ]
