# Generated by Django 5.0.4 on 2024-05-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='fecha_notificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Notificación'),
        ),
    ]
