# Generated by Django 5.0.4 on 2024-05-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_alter_notificaciones_fecha_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='tipo',
            field=models.CharField(choices=[('Certificado de enfermedad', 'Certificado de enfemedad'), ('Reclamo', 'Reclamos'), ('Permisos Especiales', 'Permisos Especiales'), ('Solicitud de Vacaciones', 'Solicitud de Vacaciones'), ('Envío de CBU', 'Envío de CBU'), ('Renuncia', 'Renuncia'), ('Otros', 'Otros')], max_length=50, verbose_name='Tipo'),
        ),
    ]
