# Generated by Django 5.0.4 on 2024-05-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0005_alter_notificaciones_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='visto',
            field=models.BooleanField(default=False, verbose_name='Visto'),
        ),
    ]
