# Generated by Django 5.0.4 on 2024-05-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0010_alter_notificaciones_visto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='visto',
            field=models.BooleanField(default=False, editable=False, verbose_name='Visto'),
        ),
    ]
