# Generated by Django 5.0.4 on 2024-05-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0011_alter_notificaciones_visto'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='notificaciones'),
        ),
    ]
