# Generated by Django 5.0.4 on 2024-05-04 12:25

import django.db.models.deletion
import empleador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=50, verbose_name='Razon Social ')),
                ('cuit', models.PositiveIntegerField(unique=True, validators=[empleador.models.validate_cuil_length], verbose_name='CUIT ')),
                ('email', models.EmailField(max_length=254, verbose_name='e-Mail ')),
            ],
            options={
                'verbose_name': 'Empleador',
                'verbose_name_plural': 'Empleadores',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido ')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre ')),
                ('cuil', models.PositiveIntegerField(unique=True, validators=[empleador.models.validate_cuil_length], verbose_name='CUIL ')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso ')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de baja ')),
                ('email', models.EmailField(max_length=254, verbose_name='e-Mail ')),
                ('empleador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleador.empleador', verbose_name='Empleador ')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_notificacion', models.DateField(auto_now=True, verbose_name='Fecha de Notificación ')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago ')),
                ('importe', models.PositiveIntegerField(verbose_name='Importe ')),
                ('liquidacion', models.CharField(choices=[('1', 'Sueldo Mensual'), ('2', 'Sueldo Quincenal'), ('3', 'Ajuste de Sueldo'), ('4', 'Otro')], max_length=20, verbose_name='Liquidación: ')),
                ('meses', models.CharField(choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=10, verbose_name='Mes: ')),
                ('año', models.PositiveIntegerField(validators=[empleador.models.validate_year_range], verbose_name='Año: ')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='archivos/recibos/')),
                ('visto', models.BooleanField(default=False, editable=False, verbose_name='Visto')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleador.empleado', verbose_name='Empleado ')),
            ],
            options={
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Suspensiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_notificacion', models.DateField(auto_now=True, verbose_name='Fecha de Notificación ')),
                ('cantidad_dias', models.PositiveIntegerField(verbose_name='Cantidad de días')),
                ('fecha_reingreso', models.DateField(verbose_name='Fecha de Reingreso ')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo ')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='archivos/suspensiones/')),
                ('visto', models.BooleanField(default=False, editable=False, verbose_name='Visto')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleador.empleado', verbose_name='Empleado ')),
            ],
            options={
                'verbose_name_plural': 'Suspensiones',
            },
        ),
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_notificacion', models.DateField(auto_now=True, verbose_name='Fecha de Notificación ')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio ')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Finalizacion ')),
                ('período', models.PositiveIntegerField(validators=[empleador.models.validate_year_range], verbose_name='Corresponden al período: ')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='archivos/vacaciones/')),
                ('visto', models.BooleanField(default=False, editable=False, verbose_name='Visto')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleador.empleado', verbose_name='Empleado ')),
            ],
            options={
                'verbose_name_plural': 'Vacaciones',
            },
        ),
    ]
