# Generated by Django 5.0.4 on 2024-04-26 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=20, verbose_name='Razon Social ')),
                ('cuit', models.IntegerField(unique=True, verbose_name='CUIT ')),
                ('email', models.EmailField(max_length=254, verbose_name='e-Mail ')),
            ],
            options={
                'verbose_name': 'Empleador',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido ')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre ')),
                ('cuil', models.IntegerField(unique=True, verbose_name='CUIT ')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso ')),
                ('email', models.EmailField(max_length=254, verbose_name='e-Mail ')),
                ('empleador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleador.empleador', verbose_name='Empleador ')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago ')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe ')),
                ('mensaje', models.CharField(max_length=50, verbose_name='Mensaje ')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleador.empleado', verbose_name='Empleado ')),
            ],
        ),
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio ')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Finalizacion ')),
                ('mensaje', models.CharField(max_length=50, verbose_name='Mensaje ')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleador.empleado', verbose_name='Empleado ')),
            ],
        ),
    ]
