# Generated by Django 5.0.4 on 2024-05-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='empleador',
            options={'verbose_name': 'Empleador', 'verbose_name_plural': 'Empleadores'},
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='vacaciones',
            options={'verbose_name_plural': 'Vacaciones'},
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cuil',
            field=models.IntegerField(unique=True, verbose_name='CUIL '),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='importe',
            field=models.PositiveIntegerField(verbose_name='Importe '),
        ),
    ]
