# Generated by Django 5.0.4 on 2024-05-04 13:15

import django.db.models.deletion
import empleador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cuil',
            field=models.PositiveIntegerField(unique=True, validators=[empleador.models.validate_cuil_length], verbose_name='CUIL'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empleador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleador.empleador', verbose_name='Empleador'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de baja'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='empleador',
            name='cuit',
            field=models.PositiveIntegerField(unique=True, validators=[empleador.models.validate_cuil_length], verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='empleador',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-Mail'),
        ),
        migrations.AlterField(
            model_name='empleador',
            name='razonSocial',
            field=models.CharField(max_length=50, verbose_name='Razon Social'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='archivos/recibos/', verbose_name='Archivo adjunto'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='año',
            field=models.PositiveIntegerField(validators=[empleador.models.validate_year_range], verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleador.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='fecha_notificacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Notificación'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='fecha_pago',
            field=models.DateField(verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='importe',
            field=models.PositiveIntegerField(verbose_name='Importe'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='liquidacion',
            field=models.CharField(choices=[('1', 'Sueldo Mensual'), ('2', 'Sueldo Quincenal'), ('3', 'Ajuste de Sueldo'), ('4', 'Otro')], max_length=20, verbose_name='Liquidación'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='meses',
            field=models.CharField(choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=10, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='suspensiones',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='archivos/suspensiones/', verbose_name='Archivo adjunto'),
        ),
        migrations.AlterField(
            model_name='suspensiones',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleador.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='suspensiones',
            name='fecha_notificacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Notificación'),
        ),
        migrations.AlterField(
            model_name='suspensiones',
            name='fecha_reingreso',
            field=models.DateField(verbose_name='Fecha de Reingreso'),
        ),
        migrations.AlterField(
            model_name='suspensiones',
            name='motivo',
            field=models.CharField(max_length=200, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='archivos/vacaciones/', verbose_name='Archivo adjunto'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleador.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha de Finalizacion'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_notificacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Notificación'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='período',
            field=models.PositiveIntegerField(validators=[empleador.models.validate_year_range], verbose_name='Corresponden al período'),
        ),
    ]
