# Generated by Django 5.0.4 on 2024-05-04 15:43

import empleador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleador', '0002_alter_empleado_apellido_alter_empleado_cuil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='fecha_notificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Notificación'),
        ),
        migrations.AlterField(
            model_name='suspensiones',
            name='fecha_notificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Notificación'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_notificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Notificación'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='período',
            field=models.PositiveIntegerField(validators=[empleador.models.validate_year_range], verbose_name='Corresponden al año'),
        ),
    ]
