# Generated by Django 5.0.4 on 2024-05-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleador', '0002_alter_empleado_options_alter_empleador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido '),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cuil',
            field=models.PositiveIntegerField(unique=True, verbose_name='CUIL '),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre '),
        ),
        migrations.AlterField(
            model_name='empleador',
            name='cuit',
            field=models.PositiveIntegerField(unique=True, verbose_name='CUIT '),
        ),
        migrations.AlterField(
            model_name='empleador',
            name='razonSocial',
            field=models.CharField(max_length=50, verbose_name='Razon Social '),
        ),
    ]
