# Generated by Django 5.0.4 on 2024-05-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleador', '0003_alter_pagos_fecha_notificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='fecha_notificacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Notificación'),
        ),
        migrations.AlterField(
            model_name='suspensiones',
            name='fecha_notificacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Notificación'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_notificacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Notificación'),
        ),
    ]
