# Generated by Django 5.0.4 on 2024-05-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleador', '0006_alter_empleador_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleador',
            name='usuario',
        ),
    ]
