# Generated by Django 5.0.4 on 2024-05-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleador', '0007_remove_empleador_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_baja',
        ),
    ]
