# Generated by Django 5.0.4 on 2024-05-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleador', '0008_remove_empleado_fecha_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='visto',
            field=models.BooleanField(default=False, verbose_name='Visto'),
        ),
        migrations.AlterField(
            model_name='suspensiones',
            name='visto',
            field=models.BooleanField(default=False, verbose_name='Visto'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='visto',
            field=models.BooleanField(default=False, verbose_name='Visto'),
        ),
    ]
