# Generated by Django 5.0.4 on 2024-05-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleador', '0009_alter_pagos_visto_alter_suspensiones_visto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='archivo_adjunto',
        ),
        migrations.RemoveField(
            model_name='suspensiones',
            name='archivo_adjunto',
        ),
        migrations.RemoveField(
            model_name='vacaciones',
            name='archivo_adjunto',
        ),
        migrations.AlterField(
            model_name='pagos',
            name='visto',
            field=models.BooleanField(default=False, editable=False, verbose_name='Visto'),
        ),
        migrations.AlterField(
            model_name='suspensiones',
            name='visto',
            field=models.BooleanField(default=False, editable=False, verbose_name='Visto'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='visto',
            field=models.BooleanField(default=False, editable=False, verbose_name='Visto'),
        ),
    ]
