# Generated by Django 5.0.4 on 2024-05-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleador', '0011_alter_pagos_liquidacion_alter_pagos_meses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='liquidacion',
            field=models.CharField(choices=[('1', 'Sueldo Mensual'), ('2', 'Sueldo Quincenal'), ('3', 'Ajuste de Sueldo'), ('4', 'Otro')], max_length=20, verbose_name='Liquidación'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='meses',
            field=models.CharField(choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=10, verbose_name='Mes'),
        ),
    ]
