# Generated by Django 5.0.4 on 2024-05-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleador', '0012_alter_pagos_liquidacion_alter_pagos_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
