# Generated by Django 5.0.4 on 2024-05-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleador', '0013_pagos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspensiones',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='suspensiones'),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vacaciones'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pagos'),
        ),
    ]
